catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.8
  vite-plus: ^0.2.8

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

allowBuilds:
  '@swc/core': false
  esbuild: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

minimumReleaseAge: 4320
